AllCops:
  NewCops: enable
  Exclude:
    - "**/vendor/**/*"

Metrics/BlockLength:
  Enabled: false

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: consistent_comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma
