AllCops:
  NewCops: enable
  Exclude:
    - "**/vendor/**/*"

Layout/EndAlignment:
  EnforcedStyleAlignWith: start_of_line

Layout/HashAlignment:
  EnforcedHashRocketStyle: table
  EnforcedColonStyle: table

Metrics/BlockLength:
  Enabled: false
